title: Functional Programming with Python 3
author: Yves Vindevogel
logo: logo.png

execute:
  execute_notebooks: force

latex:
  latex_documents:
    targetname: book.tex

bibtex_bibfiles:
  - references.bib

html:
  use_issues_button: false
  use_repository_button: false

launch_buttons:
  binderhub_url: "https://notebooks.gesis.org/binder/jupyter/user/syntra-vindevoy-nal-programming-fr7nhxnd/doc/workspaces/auto-Z/tree/book"